### ISSUE TITLE
About Betti Errors

### ISSUE THREAD

**Issue by vokcow** [nstucki/Betti-matching#1]
Hi, many thanks for this great project!

I am quite new to all this computational topology stuff. Could you please let me know if my understanding is correct:

The `Betti_number_error` method of the `BettiMatching` class will return the b0 error if dimension is 0, the b1 error if dimension is 1, and the mean of both if dimensions are [0,1]? 

Many thanks!

**Comment by nstucki** [comment]
Hi,

I am happy to hear that you like the project.

The Betti_number_error in the BettiMatching class computes the Betti_number_error. By default it computes the sum of dimension 0 and 1. But you can restrict to your dimension of interest if you set the option dim=0 or dim=1.

I hope this clarifies your question.

Best,
Nico

**Comment by vokcow** [comment]
Hi Niko, many thanks! I think then yes, setting dim=0 would compute the betti error with respect to the betti number 0 (number of connected components, or 0-dimenisonal holes) and dim=1 would do the same for the betti number 1 (number of 1-dimensional holes). Thanks! Victor.
