### ISSUE TITLE
Persistence Diagrams and BettiMatching

### ISSUE THREAD

**Issue by AmeerHamza96** [nstucki/Betti-matching#3]
While using the Betti-Matching code, persistence diagrams do not differentiate the H0 and H1 points. Is there any way to check which points correspond to H0 or H1? Also, is there any way to reduce the time to compute betti error or betti loss? Using the class BettiMatching takes some time, can we optimize this time?

**Comment by nstucki** [comment]
The persistence diagrams are given as lists of lists and the nth list contains the persistence points of dimension n.

We are working on a c++ implementation right now, which works way faster in 2D and is also applicable for 3D data. I will update you as soon as we have tested and published it.

**Comment by AmeerHamza96** [comment]
Thank you so much. I have one more concern, can we use this Betti error or Betti loss for multi-class segmentation tasks?

**Comment by nstucki** [comment]
Yes you can. We are actually testing the performance of Betti matching in this setting right now and obtain very promising results. You can, for example, apply the Betti Matching loss to every output channel of your multi-class segmentation network individually.
