### ISSUE TITLE
Request for license.txt

### ISSUE THREAD

**Issue by paulmthompson** [nstucki/Betti-matching#4]
Hi,

Could you upload a license for this project?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

"You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and _no one may reproduce, distribute, or create derivative works from your work._"

Thank you!

**Comment by nstucki** [comment]
Hi, I uploaded a license for the project. Thank you for pointing that out.
